const users = [
  {
    _id: '6401f43687b5b12bb5b34adc',
    username: 'jartsa82',
    password: '$2a$10$Gd8mjblsYlBt2EF5Xoz1p.B4WvJXKKOBcOMBQIynpY8FDpxh0ORQK',
    bio: "Hi, I'm here to help everyone!!",
    admin: false,
    createdAt: 1467638480178,
    updatedAt: 1677945307432,
    __v: 0,
    avatar: {
      url: 'http://res.cloudinary.com/dqcnxy51g/image/upload/v1677849677/codes-forum/hbi0km7azggyirzix3zc.webp',
      public_id: 'codes-forum/hbi0km7azggyirzix3zc',
    },
  },
  {
    _id: '6401f58787b5b12bb5b34b34',
    username: 'martta95',
    password: '$2a$10$1up39YZGydEy6/Rxw0Pun.3pU22SlJz6jaxsUUgxIEbs1j8hEJJny',
    avatar: {
      url: 'http://res.cloudinary.com/dqcnxy51g/image/upload/v1677849989/codes-forum/fmqqz2cjz0jeszfkerwa.webp',
      public_id: 'codes-forum/fmqqz2cjz0jeszfkerwa',
    },
    bio: "Hey, I'm here to help people!",
    admin: false,
    createdAt: 1507728391783,
    updatedAt: 1678020242363,
    __v: 0,
  },
  {
    _id: '6401f6af87b5b12bb5b34ba5',
    username: 'pertsa92',
    password: '$2a$10$Kw40N59fexpQMvifXrQ9/eS9jTUJod1dkc.DzMnBXdnlfdh8fzJtq',
    avatar: {
      url: 'http://res.cloudinary.com/dqcnxy51g/image/upload/v1677850284/codes-forum/iubgh5qlxw5roicbfjw2.webp',
      public_id: 'codes-forum/iubgh5qlxw5roicbfjw2',
    },
    bio: 'Welcome to my profile. I hope I can help you.',
    admin: false,
    createdAt: 1514813487425,
    updatedAt: 1678020386841,
    __v: 0,
  },
  {
    _id: '64048b29feca7019c1988e05',
    username: 'jukka87',
    password: '$2a$10$9NtEG/dkPHIgb6D8bDevnO0yG98KEcZUoH7XAfxEsigi3rwU62r2q',
    avatar: {
      url: 'http://res.cloudinary.com/dqcnxy51g/image/upload/v1678019369/codes-forum/dv3m6zneg4xcsnwrsinm.webp',
      public_id: 'codes-forum/dv3m6zneg4xcsnwrsinm',
    },
    bio: "I'm a software developer",
    admin: false,
    createdAt: 1404563369747,
    updatedAt: 1678019403310,
    __v: 0,
  },
  {
    _id: '641483d6c7dceae9a1cc1c9c',
    username: 'Test',
    password: '$2a$10$vo9Qmdx0RHXTaVsG1RXYT.SmwVYIHB/tNDp/pkWdm5sKxbtB2YS1C',
    bio: '',
    admin: false,
    createdAt: 1679066070842,
    updatedAt: 1679066070842,
    __v: 0,
  },
];

const posts = [
  {
    _id: '6401f4da87b5b12bb5b34aee',
    title: 'Exclude property from type',
    body: "{\"blocks\":[{\"key\":\"4e93c\",\"text\":\"I'd like to exclude a single property from the type. How can I do that?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"8cscm\",\"text\":\"For example I have\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"e4bd8\",\"text\":\"interface XYZ {\\n  x: number;\\n  y: number;\\n  z: number;\\n}\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"1ronr\",\"text\":\"And I want to exclude property z to get\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"c4j3t\",\"text\":\"type XY = { x: number, y: number };\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['TypeScript'],
    author: '6401f43687b5b12bb5b34adc',
    votes: ['6401f6af87b5b12bb5b34ba5'],
    voteCount: 1,
    createdAt: 1557235418646,
    updatedAt: 1678020401372,
    __v: 1,
  },
  {
    _id: '6401f53a87b5b12bb5b34b06',
    title: 'What is move semantics?',
    body: "{\"blocks\":[{\"key\":\"77n6h\",\"text\":\"I just finished listening to the Software Engineering radio podcast interview with Scott Meyers regarding C++0x. Most of the new features made sense to me, and I am actually excited about C++0x now, with the exception of one. I still don't get move semantics... What is it exactly?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['C++', 'C++11'],
    author: '6401f43687b5b12bb5b34adc',
    votes: ['6401f58787b5b12bb5b34b34', '6401f6af87b5b12bb5b34ba5', '6401f43687b5b12bb5b34adc'],
    voteCount: 3,
    createdAt: 1677763514718,
    updatedAt: 1677945739832,
    __v: 0,
  },
  {
    _id: '6401f56887b5b12bb5b34b18',
    title: 'How to sort a collection by date in MongoDB?',
    body: '{"blocks":[{"key":"9r3dn","text":"I am using MongoDB with Node.JS. I have a collection which contains a date and other rows. The date is a JavaScript Date object.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"dgklj","text":"How can I sort this collection by date?","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"5kr9k","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    tags: ['Node.js', 'MongoDB'],
    author: '6401f43687b5b12bb5b34adc',
    votes: ['6401f58787b5b12bb5b34b34'],
    voteCount: 1,
    createdAt: 1619097960701,
    updatedAt: 1619097960701,
    __v: 0,
  },
  {
    _id: '6401f5ee87b5b12bb5b34b49',
    title: "What's the difference between gRPC and WCF?",
    body: "{\"blocks\":[{\"key\":\"56gif\",\"text\":\"I know we are comparing 2 different technologies, but I would like to know pros and cons of both. WCF is present for almost a decade now. Didn't anything similar exist in java world until now?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['WCF', 'gRPC'],
    author: '6401f58787b5b12bb5b34b34',
    votes: ['6401f6af87b5b12bb5b34ba5'],
    voteCount: 1,
    createdAt: 1586266094575,
    updatedAt: 1586266094575,
    __v: 0,
  },
  {
    _id: '6401f63987b5b12bb5b34b5f',
    title: '.NET 6 Minimal API and multipart/form-data',
    body: "{\"blocks\":[{\"key\":\"5c44b\",\"text\":\"Using the .NET 6 Minimal API, I'm trying to handle multipart/form-data in the POST method. However, with the following code:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"5h012\",\"text\":\"app.MapPost(\\\"/tickets\\\", async (IFreshdeskApiService s, [FromForm] CreateTicketDto dto) => await s.Add(dto))\\n   .Accepts<CreateTicketDto>(\\\"multipart/form-data\\\");\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"dh71r\",\"text\":\"I'm receiving 400 Bad Request with body:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"apa98\",\"text\":\"{\\n    \\\"error\\\": \\\"Expected a supported JSON media type but got \\\\\\\"multipart/form-data; boundary=--------------------------391539519671819893009831\\\\\\\".\\\"\\n}\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"4tf7d\",\"text\":\"I switched to the non-minimal API (i.e. using app.MapControllers()), but is there any way to handle this in minimal API?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"1cjcf\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['REST', '.NET 6'],
    author: '6401f58787b5b12bb5b34b34',
    votes: [],
    voteCount: 0,
    createdAt: 1633872494575,
    updatedAt: 1633872494575,
    __v: 0,
  },
  {
    _id: '6401f69087b5b12bb5b34b7d',
    title: 'POST a Multi-Part Form to Bamboo API',
    body: "{\"blocks\":[{\"key\":\"891ff\",\"text\":\"I'm having a lot of difficulty submitting a multi-part form through a VB.NET console application to BambooHR API. I've posted my current code as well as a sample request from the documentation below, when I run this code I get (400) Bad Request. I know the code is messy, but I've just been trying to get it to work.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"270kv\",\"text\":\"I was able to make a GET request work by using their sample code, but they didn't have any code to do this specific API call (upload an employee file).\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"bnncn\",\"text\":\"ANY help would be appreciated.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"d4bbj\",\"text\":\"Here is my code:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"cot5b\",\"text\":\"Sub Main()\\n\\n    upload(id, \\\"https://api.bamboohr.com/api/gateway.php/company\\\")\\n\\n    Console.WriteLine()\\n    Console.WriteLine(\\\"Press ENTER to quit\\\")\\n    Console.ReadLine()\\nEnd Sub\\n\\nFunction upload(ByVal employeeId As Integer, ByVal baseUrl As String)\\n\\n    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 Or SecurityProtocolType.Ssl3\\n\\n    Dim boundary = \\\"----BambooHR-MultiPart-Mime-Boundary----\\\"\\n    Dim url = String.Format(\\\"{0}/v1/employees/{1}/files/\\\", baseUrl, employeeId)\\n\\n    Dim request As HttpWebRequest = WebRequest.Create(url)\\n    request.KeepAlive = True\\n    request.Method = \\\"POST\\\"\\n    request.ContentType = \\\"multipart/form-data; boundary=\\\" + boundary\\n\\n    'Authorization is just the api key and a random string, in this case is x\\n    '\\n    Dim authInfo As String = api_key + \\\":\\\" + \\\"x\\\"\\n    authInfo = Convert.ToBase64String(Encoding.Default.GetBytes(authInfo))\\n    request.Headers(\\\"Authorization\\\") = \\\"Basic \\\" + authInfo\\n\\n\\n    Dim memStream As New MemoryStream()\\n\\n    WriteMPF(memStream)\\n\\n    request.ContentLength = memStream.Length\\n\\n    Using requestStream = request.GetRequestStream()\\n        memStream.Position = 0\\n        Dim tempBuffer As Byte() = New Byte(memStream.Length - 1) {}\\n        memStream.Read(tempBuffer, 0, tempBuffer.Length)\\n        memStream.Close()\\n        requestStream.Write(tempBuffer, 0, tempBuffer.Length)\\n    End Using\\n\\n    Dim webresponse As HttpWebResponse = request.GetResponse()\\n    Return webresponse\\n\\nEnd Function\\n\\nPrivate Sub WriteMPF(s As Stream)\\n\\n    WriteToStream(s, \\\"POST /api/gateway.php/company/v1/employees/id/files/ HTTP/1.0\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Host: api.bamboohr.com\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Type: multipart/form-data; boundary=----BambooHR-MultiPart-Mime-Boundary----\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Length: 520\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, vbCr & vbLf)\\n\\n    WriteToStream(s, \\\"------BambooHR-MultiPart-Mime-Boundary----\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Disposition: form-data; name=\\\"\\\"category\\\"\\\"\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"14\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n\\n    WriteToStream(s, \\\"------BambooHR-MultiPart-Mime-Boundary----\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Disposition: form-data; name=\\\"\\\"fileName\\\"\\\"\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"test.txt\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n\\n    WriteToStream(s, \\\"------BambooHR-MultiPart-Mime-Boundary----\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Disposition: form-data; name=\\\"\\\"share\\\"\\\"\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"no\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n\\n    WriteToStream(s, \\\"------BambooHR-MultiPart-Mime-Boundary----\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Disposition: form-data; name=\\\"\\\"file\\\"\\\"; filename = \\\"\\\"test.txt\\\"\\\"\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"Content-Type: text/plain\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"this is a test!\\\")\\n    WriteToStream(s, vbCr & vbLf)\\n\\n    WriteToStream(s, vbCr & vbLf)\\n    WriteToStream(s, \\\"------BambooHR-MultiPart-Mime-Boundary------\\\")\\n    WriteToStream(s, vbCr & vbLf)\\nEnd Sub\\n\\nPrivate Sub WriteToStream(s As Stream, txt As String)\\n    Dim bytes As Byte() = Encoding.UTF8.GetBytes(txt)\\n    s.Write(bytes, 0, bytes.Length)\\nEnd Sub\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"tiff\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['VB.NET', '.NET 4.5'],
    author: '6401f58787b5b12bb5b34b34',
    votes: ['6401f6af87b5b12bb5b34ba5', '6401f58787b5b12bb5b34b34'],
    voteCount: 2,
    createdAt: 1642858256266,
    updatedAt: 1642858256266,
    __v: 0,
  },
  {
    _id: '6401f6f287b5b12bb5b34bb7',
    title: 'How to apply custom animation effect @keyframes in MUI?',
    body: "{\"blocks\":[{\"key\":\"aan9\",\"text\":\"I have learnt to use animation in CSS using @keyframe. I however want to write my custom animation code to my React project (using MUI). My challenge is how I can write the Javascript code to custom my animations using the makeStyle() in MUI.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"26tuq\",\"text\":\"I want to be able to custom the transitions processes in percentages this time around in MUI. I need to be able to write codes like this in makeStyle() but I don't seem to know how to.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"2uce3\",\"text\":\"@keyframes myEffect {\\n 0%{\\n  opacity:0;\\n  transform: translateY(-200%); \\n }\\n\\n100% {\\n  opacity:1;\\n  transform: translateY(0);\\n }\\n}\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"7j2eh\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['React.js', 'MUI', 'CSS'],
    author: '6401f6af87b5b12bb5b34ba5',
    votes: ['6401f6af87b5b12bb5b34ba5', '6401f58787b5b12bb5b34b34', '6401f43687b5b12bb5b34adc'],
    voteCount: 3,
    createdAt: 1624887154025,
    updatedAt: 1677948711292,
    __v: 0,
  },
  {
    _id: '6401f71c87b5b12bb5b34bd3',
    title: 'Programmatically navigate using React router',
    body: '{"blocks":[{"key":"6v82q","text":"With react-router I can use the Link element to create links which are natively handled by react router.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"1qoth","text":"I see internally it calls this.context.transitionTo(...).","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"490f2","text":"I want to do a navigation. Not from a link, but from a dropdown selection (as an example). How can I do this in code? What is this.context?","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"8qm19","text":"I saw the Navigation mixin, but can I do this without mixins?","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    tags: ['React.js', 'react-router'],
    author: '6401f6af87b5b12bb5b34ba5',
    votes: [],
    voteCount: 0,
    createdAt: 1641043954025,
    updatedAt: 1641043954025,
    __v: 0,
  },
  {
    _id: '6401f78987b5b12bb5b34bf1',
    title: 'Typescript typecast existing variable',
    body: "{\"blocks\":[{\"key\":\"cfuhe\",\"text\":\"Say I'm using a module of the following type:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"9hoei\",\"text\":\"interface AwesomeLibrary {\\n    name: string;\\n    query: Object;\\n}\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"2cvgr\",\"text\":\"I want to typecast query into another interface:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"7qqku\",\"text\":\"interface Query {\\n    startDate: string;\\n    endDate: string;\\n    showAll: boolean;\\n}\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"nsrn\",\"text\":\"Let's say there is a function callback that gives me the AwesomeLibrary. I want to then typecast the query into Query. Right now this is all I have:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"18olf\",\"text\":\"functionCb(response: AwesomeLibrary) {\\n    // This works fine\\n    let query: Query = response.query as Query;\\n    // Now, query.startDate is available\\n    // Do stuff to query\\n    // At the end, I want to send response back to another function, so I do\\n    response.query = query;\\n    otherFunction(response);\\n\\n    // This does not work, but basically what I want:\\n    response.query = response.query as Query;\\n    // Then do stuff to response.query directly\\n    // Here response.query.startDate is not available, instead I have to use response.query['startDate']\\n\\n    // Even this does not work:\\n    let query: Query = response.query as Query;\\n    response.query = query;\\n}\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"123sk\",\"text\":\"Thoughts?\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['TypeScript', 'JavaScript'],
    author: '6401f6af87b5b12bb5b34ba5',
    votes: ['6401f6af87b5b12bb5b34ba5'],
    voteCount: 1,
    createdAt: 1675863305757,
    updatedAt: 1686427653366,
    __v: 0,
  },
  {
    _id: '64048b9cfeca7019c1988e29',
    title: 'How to disable HTTP/2?',
    body: "{\"blocks\":[{\"key\":\"4nfj3\",\"text\":\"I want to send a fairly large number (several thousand) of HTTP requests ASAP, without putting too much load on the CDN (has an https: URL, and ALPN selects HTTP/2 during the TLS phase) So, staggering (i.e. time shifting) the requests is an option, but I don't want to wait TOO long (minimize errors AND total round-trip time) and I'm not being rate limited by the server at the scale I'm operating yet.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"9uu6s\",\"text\":\"The problem I'm seeing originates from h2_bundle.go and specifically in either writeFrame or onWriteTimeout when about 500-1k requests are in-flight, which manifests during io.Copy(fileWriter, response.Body) as:\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"dbp3t\",\"text\":\"http2ErrCodeInternal = \\\"INTERNAL_ERROR\\\" // also IDs a Stream number\\n// ^ then io.Copy observes the reader encountering \\\"unexpected EOF\\\"\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"4v69b\",\"text\":\"I'm fine sticking with HTTP/1.x for now, but I would love an explanation re: what's going on. Clearly, people DO use Go to make a lot of round-trips happen per unit time, but most advice I can find is from the perspective of the server, not clients. I've already tried specifying all the relevant time-outs I can find, and cranking up connection pool max sizes.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['Go', 'HTTP2'],
    author: '64048b29feca7019c1988e05',
    votes: ['64048b29feca7019c1988e05'],
    voteCount: 1,
    createdAt: 1667392284880,
    updatedAt: 1667392284880,
    __v: 0,
  },
  {
    _id: '64048c0bfeca7019c1988e56',
    title: 'how to use golang compress and resize a gif',
    body: '{"blocks":[{"key":"d3n9p","text":"Is there has method or lib to compress and resize a gif use golang?","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"987hh","text":"ps: I was tried bimg, but it not support gif.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"f04sq","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    tags: ['Go', 'Gif'],
    author: '64048b29feca7019c1988e05',
    votes: [],
    voteCount: 0,
    createdAt: 1550406795483,
    updatedAt: 1550406795483,
    __v: 0,
  },
  {
    _id: '64048c38feca7019c1988eac',
    title: 'Simple Golang GraphQL Server',
    body: '{"blocks":[{"key":"62vbm","text":"Does a simple & working \\"Hello World!\\" GraphQL server code in Go exist?","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"9p56c","text":"There is a deficiency in tutorials concerning that topic, especially because graphql-go/graphql is currently a work-in-progress.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    tags: ['Go', 'GraphQL'],
    author: '64048b29feca7019c1988e05',
    votes: ['64048b29feca7019c1988e05', '6401f6af87b5b12bb5b34ba5'],
    voteCount: 2,
    createdAt: 1575808395483,
    updatedAt: 1678020400357,
    __v: 1,
  },
  {
    _id: '64048c66feca7019c1988ed6',
    title: 'HTTP Basic Auth with Golang',
    body: '{"blocks":[{"key":"4hua6","text":"How do I implement basic auth with a Golang site? So that when someone visits a page they will be prompted by their browser with a login.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    tags: ['Go', 'Authentication'],
    author: '64048b29feca7019c1988e05',
    votes: ['64048b29feca7019c1988e05'],
    voteCount: 1,
    createdAt: 1677933286402,
    updatedAt: 1686427595015,
    __v: 0,
  },
  {
    _id: '64048dd8feca7019c198903c',
    title: 'How do I add TypeScript to my existing Vite (React) application?',
    body: "{\"blocks\":[{\"key\":\"csvhb\",\"text\":\"I have an existing react app which I created using Vite. I used the react template in Vite-\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"3aji5\",\"text\":\"yarn create vite my-react-app --template react\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"4s75i\",\"text\":\"As the project progressed, it seemed a good idea to include TypeScript for stricter type checking. I had earlier included TypeScript in one of my existing projects using create-react-app with the help of this clear documentation. I tried incorporating the same in my Vite app. I executed the following code in my terminal -\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"b8mvd\",\"text\":\"yarn add typescript @types/node @types/react @types/react-dom @types/jest\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"8urm2\",\"text\":\"I renamed my .jsx files to .tsx and my vite.config.js to vite.config.ts and restarted my vite server.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"6fssf\",\"text\":\"But to my utter dismay, the app stopped working. I couldn't find any documentation in the vite docs for adding TypeScript to an existing app. I also searched in the Vite Github community, but couldn't find anything relatable there. I couldn't find anything related to this on the web too. Most of the stuff is on CRA and Typescript.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"bbda\",\"text\":\"Any help on this would be appreciated. Thanks!\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    tags: ['Vite', 'React.js', 'TypeScript'],
    author: '6401f6af87b5b12bb5b34ba5',
    votes: ['641483d6c7dceae9a1cc1c9c'],
    voteCount: 1,
    createdAt: 1578141656617,
    updatedAt: 1679066081583,
    __v: 0,
  },
];

const comments = [
  {
    _id: '6401f7b287b5b12bb5b34c45',
    body: '{"blocks":[{"key":"3m73i","text":"Great question!","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    post: '6401f69087b5b12bb5b34b7d',
    author: '6401f6af87b5b12bb5b34ba5',
    votes: [],
    voteCount: 0,
    createdAt: 1677850546235,
    updatedAt: 1677850546235,
    __v: 0,
  },
  {
    _id: '6401f7fe87b5b12bb5b34c96',
    body: '{"blocks":[{"key":"co6ob","text":"I have no idea!","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    post: '6401f71c87b5b12bb5b34bd3',
    author: '6401f58787b5b12bb5b34b34',
    votes: [],
    voteCount: 0,
    createdAt: 1677850622832,
    updatedAt: 1677850622832,
    __v: 0,
  },
  {
    _id: '6401f87c87b5b12bb5b34d11',
    body: '{"blocks":[{"key":"cddn8","text":"It is a very good feature!","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    post: '6401f53a87b5b12bb5b34b06',
    author: '6401f6af87b5b12bb5b34ba5',
    votes: [],
    voteCount: 0,
    createdAt: 1677850748683,
    updatedAt: 1677850748683,
    __v: 0,
  },
  {
    _id: '64036546553845fcc941e63f',
    body: '{"blocks":[{"key":"35ri0","text":"Thank you! Very much!","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    post: '6401f53a87b5b12bb5b34b06',
    author: '6401f43687b5b12bb5b34adc',
    votes: [],
    voteCount: 0,
    createdAt: 1677944134973,
    updatedAt: 1677944134973,
    __v: 0,
  },
  {
    _id: '64048f3efeca7019c19891bf',
    body: '{"blocks":[{"key":"58k59","text":"Yes, it does!","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    post: '64048c38feca7019c1988eac',
    author: '6401f6af87b5b12bb5b34ba5',
    votes: ['6401f6af87b5b12bb5b34ba5'],
    voteCount: 1,
    createdAt: 1678020414131,
    updatedAt: 1678020418241,
    __v: 0,
  },
  {
    _id: '64148425c7dceae9a1cc1cba',
    body: '{"blocks":[{"key":"tb08","text":"Comment test!","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
    post: '64048dd8feca7019c198903c',
    author: '641483d6c7dceae9a1cc1c9c',
    votes: [],
    voteCount: 0,
    createdAt: 1679066149970,
    updatedAt: 1679066149970,
    __v: 0,
  },
];

export default { users, posts, comments };
